### ISSUE TITLE
error occur

### ISSUE THREAD

**Issue by huahangc** [YuelangX/Gaussian-Head-Avatar#21]
```Traceback (most recent call last):
  File "train_meshhead.py", line 8, in <module>
    from lib.dataset.DataLoaderX import DataLoaderX
  File "/home/hh/PythonCode/Gaussian-Head-Avatar/lib/dataset/DataLoaderX.py", line 2, in <module>
    from prefetch_generator import BackgroundGenerator
ModuleNotFoundError: No module named 'prefetch_generator'
```
I cant find the prefetch_generator module in the code. How to solve this?

**Comment by huahangc** [comment]
Sorry, its not a customize library. It should pip install.
