### ISSUE TITLE
Inference Pipeline

### ISSUE THREAD

**Issue by waleedrazakhan92** [YuelangX/Gaussian-Head-Avatar#31]
Hello, thank you for this great work. I'm having some trouble getting this to run. I've installed both diff-gaussian-rasterization and simple-knn. Downloaded the mini_demo_dataset to check the workings of the code but when i try to run `python train_meshhead.py --config config/train_meshhead_N031.yaml` command, i get the following error even though I've changed the path of the dataset in the  config file. 

`/content/Gaussian-Head-Avatar
Traceback (most recent call last):
  File "/content/Gaussian-Head-Avatar/train_meshhead.py", line 7, in <module>
    from lib.dataset.Dataset import MeshDataset
  File "/content/Gaussian-Head-Avatar/lib/dataset/Dataset.py", line 12, in <module>
    from pytorch3d.renderer.cameras import look_at_view_transform
  File "/usr/local/lib/python3.10/dist-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/usr/local/lib/python3.10/dist-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
 `
 
 If anyone who has success running the code please guide me or share their notebook and/or environment, that would be great. 
P.S I'm running this on Google Colab.

**Comment by YuelangX** [comment]
I guess this is due to the version mismatch of cuda pytorch and pytorch3d.
